#ifndef CONSTANTS_INCLUDED
#define WORDLENGTH 11
#define NUMWORDS 65536
#define WORDFILE "words.txt"
#define HEX_CHUNK_LENGTH 4
#define HEX_CHUNK_FORMAT "%04X"
#define ERR_MSG_LENGTH 64
#define CONSTANTS_INCLUDED
#endif
